%======== BEGIN inserted by add_gemeinsam.rb ======================
\documentclass{beamer}
\input{../gemeinsam.tex}
\begin{document}
\lstset{language=Ruby}
\lstset{basicstyle=\small,numbers=none, numberstyle=\tiny, numbersep=5pt}
%======== END inserted by add_gemeinsam.rb ======================
\begin{frame}
  \frametitle{Exceptions}
  Exceptions
  \lstinputlisting[frame=single,caption={ex1}]{code/ex1.rb}
\end{frame}

\begin{frame}
  \frametitle{Exceptions}
  Ergebnis
  \lstinputlisting[frame=single,caption={ex1\_ergebnis}]{code/ex1_ergebnis}
\end{frame}

\begin{frame}
  \frametitle{Exceptions}
  Exception wird abgefangen
  \lstinputlisting[frame=single,caption={ex2.rb}]{code/ex2.rb}
\end{frame}

\begin{frame}
  \frametitle{Exceptions}
  Ergebnis
  \lstinputlisting[frame=single,caption={ex2\_ergebnis}]{code/ex2_ergebnis}
\end{frame}

\begin{frame}
  \frametitle{Exceptions}
  Exceptions-Hierarchie
  \lstinputlisting[frame=single,caption={Exceptions-Hierarchie}]{code/exceptions.txt}
\end{frame}


\begin{frame}
  \begin{itemize}
    \item Exceptions sind Objekte
    \pause
    \item \texttt{rescue xxx} f"angt alle Exceptions mit diesem Namen und alle Subclasses ab.
    \pause
    \item Name der Exception bei \texttt{rescue} kann entfallen. Default-Wert ist \texttt{StandardError}
    \pause
    \item Mehrere \texttt{rescue}-Klauseln m"oglich
    \pause
    \item Mehrere Exceptions bei \texttt{rescue} m"oglich
    \pause
    \item Globale Variable \texttt{\$!} enth"alt letzte ausgel"oste Exceptions
  \end{itemize}
\end{frame}

\begin{frame}
  \frametitle{Exceptions}
  Letzte Exception erneut ausl"osen
  \lstinputlisting[frame=single,caption={ex3.rb}]{code/ex3.rb}
\end{frame}

\begin{frame}
  \frametitle{Exceptions}
  ensure
  \lstinputlisting[frame=single,caption={ensure.rb}]{code/ensure.rb}
  Ensure-Klausel wird in jedem Fall ausgef"uhrt, egal ob eine Exception auftritt oder nicht
\end{frame}

\begin{frame}
  \frametitle{Exceptions}
  else
  \lstinputlisting[frame=single,caption={else.rb}]{code/else.rb}
  Else-Klausel wird ausgef"uhrt falls keine Exception auftritt
\end{frame}

\begin{frame}
  \frametitle{Exceptions}
  retry
  \lstinputlisting[frame=single,caption={retry.rb}]{code/retry.rb}
  Retry startet den Block neu
\end{frame}

\begin{frame}
  \frametitle{Exceptions}
  Exceptions selbst ausl"osen
  \begin{itemize}[<+->]
    \item \texttt{raise} \\
      $\longrightarrow$ \texttt{raise\_exceptons.rb:1:in \`<main>\': unhandled exception}
    \item{raise 'Missing name' if name.nil?} \\
      $\longrightarrow$ \texttt{raise\_exceptons.rb:3:in \`<main>\': Missing name (RuntimeError)}
    %\item \texttt{{if i >= names.size\\
  %raise IndexError, ''#\{i\} >= size (#\{names.size\})''\\
%end} \\
      %\texttt{raise\_exceptons.rb:9:in \`<main>\': 5 >= size (3) (IndexError)}
    \item \texttt{raise ArgumentError, 'Name too big', caller} \\
          $\longrightarrow$ \texttt{raise\_exceptons.rb:14:in \`<main>\': Name too big (ArgumentError)}
  \end{itemize}
\end{frame}

\begin{frame}
  \frametitle{Exceptions}
  Eigene Exceptions definieren 
  \begin{itemize}
    \item \texttt{class MeineException < RuntimeError \\
end \\
raise MeineException.new, 'dies ist der Text'}  \\
\vspace{3ex}$\longrightarrow$ \texttt{raise\_exceptons.rb:19:in \`<main>\': dies ist der Text (MeineException)}
    \item Parameter"ubergabe bei new ist auch m"oglich\\
          \texttt{raise MeineException.new('hugo'), 'Fehler aufgetreten'}
  \end{itemize}
\end{frame}

\begin{frame}
  \frametitle{Catch / Throw}
  Catch / Throw
  \lstinputlisting[frame=single,caption={catch\_throw.rb}]{code/catch_throw.rb}
\vspace{3ex}'throw' mu"s im Code nicht innerhalb des 'catch' Blocks auftauchen, sondern kann auch au"serhalb stehen.
\end{frame}

%======== BEGIN inserted by add_gemeinsam.rb ======================
\end{document}
%======== END inserted by add_gemeinsam.rb ======================
